# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poraba_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avtomobil',
            old_name='ime',
            new_name='ime_vozila',
        ),
        migrations.AlterField(
            model_name='avtomobil',
            name='tip_goriva',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user2',
            name='tip_voznika',
            field=models.CharField(max_length=45),
        ),
    ]
