# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poraba_app', '0002_auto_20170104_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='strosek',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
