# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poraba_app', '0003_auto_20170104_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User2',
            new_name='Profile',
        ),
    ]
