# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poraba_app', '0006_auto_20170104_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='poraba',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
